name: node

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript
      - name: Build
        run: npm run build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Test
        run: npm run test
      - name: Report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
